spring.application.name=hoodie-app
spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce_app
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
#spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.sql.init.mode=always
server.port=8081
jwt.secret=mySecretKeyAtLeast32CharactersLongForHS512AlgorithmValidateForDeveloper
# jwt.expiration=86400000
jwt.access-token-expiration=3600000
jwt.refresh-token-expiration=86400000
# Log SQL jOOQ
logging.level.org.jooq.tools.LoggerListener=DEBUG
logging.level.org.jooq.ExecuteListener=DEBUG
# production
# logging.level.org.jooq=INFO
# spring.jooq.settings.execute-logging=false